version: "3.7"
services:

  proxy-mssql-backend:
    build:
      context: .
      dockerfile: Dockerfile-proxy-backend
    networks:
      cloud-private:
    ports:
    - "443:443"


  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=mssql1Ipw
    networks:
      cloud-private:

networks:
  cloud-private:
    name: cloud-private

