version: "3.7"
services:

  app:
    build:
      context: .
      dockerfile: Dockerfile-app
    networks:
      onprem-db-zone:
      onprem-office-lan:
      

  proxy-mssql-frontend:
    build:
      context: .
      dockerfile: Dockerfile-proxy-frontend-no-tls
    networks:
      onprem-db-zone:
        aliases:
        - sqlserver
      public-network:

  proxy-mssql-backend:
    build:
      context: .
      dockerfile: Dockerfile-proxy-backend-no-tls
    networks:
      cloud-private:
      public-network:
        aliases:
        - proxy-sqlserver-backend.mydomain.com


  sqlserver:
    image: justin2004/mssql_server_tiny
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=mssql1Ipw
    networks:
      cloud-private:

networks:
  cloud-private:
    name: cloud-private
  onprem-db-zone:
    name: onprem-db-zone
  onprem-office-lan:
    name: onprem-office-lan
  public-network:
    name: public-network
