FROM envoyproxy/envoy-dev:latest

COPY ./envoy-frontend-http.yaml /etc/envoy.yaml
COPY ./certs/ca.crt /certs/cacert.pem
COPY ./certs/sqlserver-frontend.mydomain.com.crt /certs/clientcert.pem
COPY ./certs/mydomain.com.key /certs/clientkey.pem

RUN chmod go+r /etc/envoy.yaml /certs/cacert.pem /certs/clientkey.pem /certs/clientcert.pem
CMD ["/usr/local/bin/envoy", "-c /etc/envoy.yaml", "-l", "debug"]
