version: "3.7"
services:

  app:
    build:
      context: .
      dockerfile: Dockerfile-app
    networks:
      onprem-db-zone:
      onprem-office-lan:
    
      

  proxy-mssql-frontend:
    build:
      context: .
      dockerfile: Dockerfile-proxy-frontend-no-tls
    networks:
      onprem-db-zone:
        aliases:
        - sqlserver

  
networks:
  onprem-db-zone:
    name: onprem-db-zone
  onprem-office-lan:
    name: onprem-office-lan
